### ISSUE TITLE
Log Viewer error

### ISSUE THREAD

**Issue by amol-anand** [adobe/helix-tools-website#31]
Customer (TCCC) ran into the following error while viewing logs. Some specific log is causing this issue. Need to investigate further.

#### Logs taken while reproducing problem
```
Cannot read properties of undefined (reading 'map')
    at RewrittenData.path (scripts.js:225:39)
    at scripts.js:266:35
    at Array.forEach (<anonymous>)
    at RewrittenData.rewrite (scripts.js:264:10)
    at buildLog (scripts.js:294:17)
    at scripts.js:311:17
    at Array.forEach (<anonymous>)
    at displayLogs (scripts.js:310:8)
    at fetchLogs (scripts.js:373:7)
```

**Comment by amol-anand** [comment]
Issue seems to be with the `sitemap` entry in the audit log
